name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "30 14 * * *"

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      min_version: 2.5

  yamatanooroti:
    needs: ruby-versions
    name: >-
      yamaoro ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        os: [ ubuntu-latest ]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install libvterm
        run: |
          sudo apt install -y libtool-bin
          wget http://www.leonerd.org.uk/code/libvterm/libvterm-0.1.4.tar.gz
          tar xvzf libvterm-0.1.4.tar.gz
          cd libvterm-0.1.4
          sed -i -e 's/^PREFIX=.*$/PREFIX=\/usr/g' Makefile
          make
          sudo make install
      - name: rake test
        run: |
          bundle install
          bundle exec rake test
  windows-yamatanooroti:
    needs: ruby-versions
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }} ${{ matrix.console }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019, windows-2022 ]
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        console: [ conhost, legacy-conhost, stable ]
        exclude:
          - ruby: 2.5
          - console: stable
            os: windows-2019
          - console: legacy-conhost
            os: windows-2022
        include:
          - os: windows-2022
            ruby: 3.3
            console: preview
          - os: windows-2022
            ruby: 3.3
            console: canary
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: rake test
        run: |
          bundle install
          bundle exec rake test TESTOPTS="-v --wt_dir=./tmp --windows=${{ matrix.console }}"
